import datetime
import json
from sqlalchemy import Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from models.base import Base


class Calculation(Base):
    """A stored engineering calculation with formula, variables, and result."""

    __tablename__ = "calculations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    project_id: Mapped[int] = mapped_column(ForeignKey("projects.id"), nullable=False)
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    description: Mapped[str] = mapped_column(Text, default="")

    # JSON-encoded dict: {"F": {"value": 100, "unit": "kN"}, "A": {"value": 0.05, "unit": "m**2"}}
    variables_json: Mapped[str] = mapped_column(Text, default="{}")

    # The formula expression, e.g. "F / A"
    formula: Mapped[str] = mapped_column(Text, nullable=False)

    # Computed result stored for reference
    result_value: Mapped[str] = mapped_column(String(200), default="")
    result_unit: Mapped[str] = mapped_column(String(100), default="")

    # LaTeX rendering of the formula (generated by sympy)
    formula_latex: Mapped[str] = mapped_column(Text, default="")

    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime, default=datetime.datetime.utcnow
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow
    )

    project: Mapped["Base"] = relationship("Project", back_populates="calculations")

    # --- helpers ---

    def get_variables(self) -> dict:
        return json.loads(self.variables_json) if self.variables_json else {}

    def set_variables(self, variables: dict):
        self.variables_json = json.dumps(variables)

    def __repr__(self) -> str:
        return f"<Calculation {self.id}: {self.title}>"
